baseurl = "https://qe-community.github.io/"  # Include trailing slash
languageCode = "zh-cn"
title = "QE Community"
theme = "hugo-swift-theme"
author = "Steve Francia"
copyright = "Copyright © 2008–2018, Steve Francia and the Hugo Authors; all rights reserved."
canonifyurls = true
paginate = 10
# Enable syntax highlighting
# comment on delete the following lines 11 ~ 13
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true

[params]
  blogDir = "posts" # uncomment and edit to exclude normal pages ... see issue #57
  # ga_analytics = "" # google analytics ID e.g UA-116386578-1
  # ga_verify = "" # google verification code e.g 5jb-rxeBfITeJQKOuUss3ud6FPGTxXkCho-ZN5qlrZg
  # twitter = "" # twitter handle e.g @weru
  # logo = "logo.png"
  # author = "Weru" # default author
  # image = "placeholder-image.png" # used whenever a page image is not set
  [params.designer]
    name = "Weru"
    url = "https://www.linkedin.com/in/dan-weru-profile/"
  [[params.authors]]
    name = "authorA"
    fullName = "Name A"
    bio = "It's time to flex. Write a short or not-so-short summary about yourself."
    photo = "/images/avatar.png"
    url = "/authors/author1"
  [[params.authors]]
    name = "authorB"
    fullName = "Name B"
    bio = "It's time to flex. Write a short or not-so-short summary about yourself."
    photo = "/images/avatar2.png"
    url = "/authors/author2"
  
# [params.staticman]
#   endpoint = ""  # URL of your own API deployment (without trailing slash), default: "https://staticman-frama.herokuapp.com"
#   gitProvider = "github"  # Either "github" or "gitlab"
#   username = "username"  # GitHub/GitLab user name
#   repository = "repo"  # GitHub/GitLab user name
#   branch = "master"  # Branch holding the source code for your site, should match the `branch` parameter in `staticman.yml`
#
#   # If you use reCAPTCHA v2, you must also set these parameters in staticman.yml
#   [Params.staticman.reCaptcha]
#     siteKey = ""  # Use your own site key, you need to apply for one on Google
#     secret  = ""  # ENCRYPT your password by going to https://<staticman-endpoint>/v3/encrypt/<your-site-secret>

[menu]
  [[menu.main]]
    name = "About"
    url = "about/"
    weight = 2
  [[menu.main]]
    name = "Authors"
    url = "/authors"
    weight = 3
